// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_poll_id_ from "./routes/api/poll/[id].ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $poll_id_results from "./routes/poll/[id]/results.tsx";
import * as $poll_id_share from "./routes/poll/[id]/share.tsx";
import * as $poll_id_vote from "./routes/poll/[id]/vote.tsx";
import * as $poll_new from "./routes/poll/new.tsx";
import * as $AutoRefreshingBarGraph from "./islands/AutoRefreshingBarGraph.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ShareButton from "./islands/ShareButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/poll/[id].ts": $api_poll_id_,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/poll/[id]/results.tsx": $poll_id_results,
    "./routes/poll/[id]/share.tsx": $poll_id_share,
    "./routes/poll/[id]/vote.tsx": $poll_id_vote,
    "./routes/poll/new.tsx": $poll_new,
  },
  islands: {
    "./islands/AutoRefreshingBarGraph.tsx": $AutoRefreshingBarGraph,
    "./islands/Counter.tsx": $Counter,
    "./islands/ShareButton.tsx": $ShareButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
